#!/bin/bash
timedatectl set-ntp true
drive="/dev/sda"
sfdisk $drive -f -X dos << EOF
,1048576,L,*
;
EOF
mkfs.fat -F32 $drive"1"
mkfs.ext4 $drive"2"
mount $drive"2" /mnt
mkdir /mnt/boot
mount $drive"1" /mnt/boot
pacstrap /mnt base base-devel linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt /bin/bash <<"EOT"
yes | pacman -S networkmanager grub efibootmgr vim neofetch htop curl
systemctl enable --now NetworkManager
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
echo -e "licht\nlicht" | passwd
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo "LANG=en-US.UTF-8" > /etc/locale.conf
echo "mail" > /etc/hostname
ln -sf /usr/share/zoneinfo/Europe/Zurich /etc/localtime
echo "[[ -f ~/.profile ]] && . ~/.profile" > ~/.bash_profile
yes | pacman -S net-tools docker docker-compose git
netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995|4190|5222|5269|5443'
systemctl enable --now docker
umask
cd /opt
git clone https://github.com/mailcow/mailcow-dockerized
exit
EOT
umount -R /mnt
reboot