#!/bin/bash
timedatectl set-ntp true
drive="/dev/sda"
sfdisk $drive -f -X dos << EOF
,1048576,L,*
;
EOF
mkfs.fat -F32 $drive"1"
mkfs.ext4 $drive"2"
mount $drive"2" /mnt
mkdir /mnt/boot
mount $drive"1" /mnt/boot
pacstrap /mnt base base-devel linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt /bin/bash <<"EOT"
yes | pacman -S networkmanager grub efibootmgr vim neofetch htop curl
systemctl enable --now NetworkManager
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
echo -e "licht\nlicht" | passwd
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo "LANG=en-US.UTF-8" > /etc/locale.conf
echo "mail" > /etc/hostname
ln -sf /usr/share/zoneinfo/Europe/Zurich /etc/localtime
echo "[[ -f ~/.profile ]] && . ~/.profile" > ~/.bash_profile
yes | pacman -S net-tools docker docker-compose git
systemctl enable --now docker



netstat -tulpn | grep -E -w '80|8080'
cd /usr/local
git clone https://github.com/searx/searx-docker.git
cd searx-docker
sed -i "s|ReplaceWithARealKey\!|$(openssl rand -base64 33)|g" .env
timeout 30 ./start.sh
cp searx-docker.service.template searx-docker.service
systemctl enable $(pwd)/searx-docker.service
systemctl start searx-docker.service

exit
EOT
umount -R /mnt
reboot